/**                                                                      
 * @file    version.h                                                    
 * @brief   Git tag and commit information                               
 * @warning DO NOT EDIT!                                                 
 *          Generated by GetGitVersion.cmd                               
 */                                                                      
                                                                         
#ifndef BUILD_INFO_H                                                     
#define BUILD_INFO_H                                                     
                                                                         
#define BUILD_DATE    "2020-01-08"                                     
                                                                         
#define BUILD_TIME    "22:47:35"                                     
                                                                         
#define BUILD_INFO    "e5faf73"                                     
                                                                         
#define BUILD_BRANCH  "master"                                   
                                                                         
#endif /* BUILD_INFO_H */                                                
                                                                         
