@rem === Batch file to generate commit information from the git tag and log information.===


@rem === Get Git Commit Info ===

@git rev-parse --short HEAD > tmp.txt
@set /p COMMIT_INFO=<tmp.txt
@del tmp.txt

@rem  -------------------------------------------------------------------

@git branch > tmp.txt
@set /p COMMIT_BRANCHES=<tmp.txt
@del tmp.txt

@rem  -------------------------------------------------------------------

@rem === Get Git Commit Date & Time ===

@git log -1 --format=%%ci > tmp.txt
@set /p COMMIT_FULL_DATE=<tmp.txt
@for /F "usebackq tokens=1-4 delims=/ " %%I IN (`@echo %COMMIT_FULL_DATE%`) do @set COMMIT_DATE=%%I
@for /F "usebackq tokens=1-4 delims=/ " %%I IN (`@echo %COMMIT_FULL_DATE%`) do @set COMMIT_TIME=%%J
@for /F "usebackq tokens=1-4 delims=/ " %%I IN (`@echo %COMMIT_BRANCHES%`)  do @set COMMIT_BRANCH=%%J
@del tmp.txt

@rem  -------------------------------------------------------------------

@set COMMIT_INFO_FILE=Version.h

@rem === Create Commit Info Header File ===
@echo[
@echo -------------------------------------------------------------------
@echo Commit Info: %COMMIT_BRANCH% %COMMIT_INFO% %COMMIT_DATE% %COMMIT_TIME% into %COMMIT_INFO_FILE%
@echo -------------------------------------------------------------------
@echo[
@echo /**                                                                      >  %COMMIT_INFO_FILE%
@echo  * @file    Version.h                                                    >> %COMMIT_INFO_FILE%
@echo  * @brief   Git tag and commit information                               >> %COMMIT_INFO_FILE%
@echo  * @warning DO NOT EDIT!                                                 >> %COMMIT_INFO_FILE%
@echo  *          Generated by GetGitVersion.cmd                               >> %COMMIT_INFO_FILE%
@echo  */                                                                      >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #ifndef COMMIT_INFO_H                                                     >> %COMMIT_INFO_FILE%
@echo #define COMMIT_INFO_H                                                     >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #define COMMIT_DATE    "%COMMIT_DATE%"                                     >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #define COMMIT_TIME    "%COMMIT_TIME%"                                     >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #define COMMIT_INFO    "%COMMIT_INFO%"                                     >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #define COMMIT_BRANCH  "%COMMIT_BRANCH%"                                   >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%
@echo #endif /* COMMIT_INFO_H */                                                >> %COMMIT_INFO_FILE%
@echo[                                                                         >> %COMMIT_INFO_FILE%

@rem  -------------------------------------------------------------------

