/**                                                                      
 * @file    Version.h                                                    
 * @brief   Git tag and commit information                               
 * @warning DO NOT EDIT!                                                 
 *          Generated by GetVersion.cmd                                  
 */                                                                      
                                                                         
#ifndef COMMIT_INFO_H                                                    
#define COMMIT_INFO_H                                                    
                                                                         
#if _MSC_VER 
#pragma execution_character_set("utf-8")                                 
#endif                                                                   
                                                                         
#define DEV_VERSION    "Milestone 2"                                     
                                                                         
#define DEV_ENV        "Qt 5.6.3 (MSVC 2015, 32bit)"                     
                                                                         
#define BUILD_COUNTER  "138"                                 
                                                                         
#define COMMIT_DATE    "2020-04-04"                                   
                                                                         
#define COMMIT_TIME    "02:31:40"                                   
                                                                         
#define COMMIT_INFO    "b069a4c"                                   
                                                                         
#define COMMIT_BRANCH  "master"                                 
                                                                         
#endif /* COMMIT_INFO_H */                                               
                                                                         
